global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'webhook'

receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'https://script.google.com/macros/s/AKfycbx8pBkCJr5MyJFXoueBloaCjJDUXCa-OjZVbifFY7kdFnLkAljVfqxnh_6ZJdpcDHnQ/exec'
    send_resolved: true
