global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001'] 
      
  - job_name: 'strapi'
    metrics_path: '/api/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['strapi:1338']
      
  - job_name: 'cadvisor'
    scheme: 'http'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093'] 
